name: Container Workflow
on:
  push:
  workflow_dispatch:

env:
  ACR_LOGON_SERVER: acrtestnm.azurecr.io
  IMAGE_NAME: acrtestnm.azurecr.io/webapp:${{ github.sha }}

jobs:
    build-deploy-image:
        
        runs-on: ubuntu-latest
        
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
          
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ env.ACR_LOGON_SERVER }}
            username: ${{ secrets.SERVICE_PRINCIPAL_ID }}
            password: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}

        - run: docker build ./WebApplication3/Dockerfile -t ${{ env.IMAGE_NAME }}
        - run: docker push ${{ env.IMAGE_NAME }}
